image: gcc

# Defines stages which are to be executed
stages:
- compile-linux-qt
- compile-windows-qt
- compile-mac-qt

build-unix:
  stage: compile-linux-qt
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  script:
  - apt update && apt -y install make autoconf
  - cd depends
  - make HOST=x86_64-pc-linux-gnu
  - cd ../
  - ./autogen.sh
  - ./configure --enable-cxx --disable-shared --without-gui --disable-tests --prefix=`pwd`/depends/x86_64-pc-linux-gnu
  - make
  when: manual
  # The files which are to be made available in GitLab
  artifacts:
    paths:
    #- src/qt/bltg-qt
    - src/bltgd
    - src/bltg-cli
    - src/bltg-tx

build-win64:
  stage: compile-windows-qt
  script:
  - apt update && apt -y install make autoconf g++-mingw-w64-x86-64
  - cd depends
  - make HOST=x86_64-w64-mingw32
  - cd ../
  - ./autogen.sh
  - ./configure --enable-cxx --disable-shared --disable-tests --prefix=`pwd`/depends/x86_64-w64-mingw32
  - make
  when: manual
  # The files which are to be made available in GitLab
  artifacts:
    paths:
    - src/qt/bltg-qt.exe
    - src/bltgd.exe
    - src/bltg-cli.exe
    - src/bltg-tx.exe
cache:
  paths:
  - "depends/x86_64-pc-linux-gnu"
  - "depends/x86_64-w64-mingw32"
  #- "depends/x86_64-pc-linux-gnu"